/** Canonical structured log event names for critical LMS admin actions. */
export const LMS_ACTION_EVENTS = Object.freeze({
  IMPORT_STARTED: 'IMPORT_STARTED',
  IMPORT_COMPLETED: 'IMPORT_COMPLETED',
  IMPORT_FAILED: 'IMPORT_FAILED',
  TEST_EXPORT_STARTED: 'TEST_EXPORT_STARTED',
  TEST_EXPORT_COMPLETED: 'TEST_EXPORT_COMPLETED',
  TEST_EXPORT_FAILED: 'TEST_EXPORT_FAILED',
  TEST_IMPORT_STARTED: 'TEST_IMPORT_STARTED',
  TEST_IMPORT_COMPLETED: 'TEST_IMPORT_COMPLETED',
  TEST_IMPORT_FAILED: 'TEST_IMPORT_FAILED',
  PUBLISH_STARTED: 'PUBLISH_STARTED',
  PUBLISH_COMPLETED: 'PUBLISH_COMPLETED',
  TEST_CREATED: 'TEST_CREATED',
  TEST_UPDATED: 'TEST_UPDATED',
});
