/**
 * Stable, machine-readable error codes for API responses, logging, analytics, and future i18n.
 *
 * Naming convention:
 * - SCREAMING_SNAKE_CASE
 * - Domain-prefixed where ambiguity exists (e.g. ACCESS_* for entitlement)
 * - Immutable once released — add new codes; never rename in place
 */

/** Authentication & session */
export const AUTH_REQUIRED = 'AUTH_REQUIRED';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const ADMIN_ACCESS_REQUIRED = 'ADMIN_ACCESS_REQUIRED';
export const STUDENT_ACCESS_REQUIRED = 'STUDENT_ACCESS_REQUIRED';
export const EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED';
export const STEP_UP_REQUIRED = 'STEP_UP_REQUIRED';
export const ACCOUNT_RISK_BLOCKED = 'ACCOUNT_RISK_BLOCKED';

/** Entitlement & enrollment access */
export const ENROLLMENT_NOT_FOUND = 'ENROLLMENT_NOT_FOUND';
export const ACCESS_EXPIRED = 'ACCESS_EXPIRED';
export const ACCESS_REVOKED = 'ACCESS_REVOKED';
export const ACCESS_INACTIVE = 'ACCESS_INACTIVE';
export const MULTIPLE_ACTIVE_ENROLLMENTS = 'MULTIPLE_ACTIVE_ENROLLMENTS';
export const COURSE_ACCESS_MISMATCH = 'COURSE_ACCESS_MISMATCH';
export const INVALID_ENTITLEMENT_STATE = 'INVALID_ENTITLEMENT_STATE';
export const COURSE_NOT_ACCESSIBLE = 'COURSE_NOT_ACCESSIBLE';
export const ENTITLEMENT_REQUIRED = 'ENTITLEMENT_REQUIRED';
export const ENROLLMENT_ACTIVATION_DENIED = 'ENROLLMENT_ACTIVATION_DENIED';
export const ENROLLMENT_INTEGRITY_VIOLATION = 'ENROLLMENT_INTEGRITY_VIOLATION';
export const ENROLLMENT_SWITCH_CONFIRMATION_REQUIRED = 'ENROLLMENT_SWITCH_CONFIRMATION_REQUIRED';
export const DUPLICATE_ACTIVE_ENROLLMENT = 'DUPLICATE_ACTIVE_ENROLLMENT';
export const PREMIUM_ACCESS_PROTECTED = 'PREMIUM_ACCESS_PROTECTED';
/** Course admissions closed — new enrollments blocked (existing students retain access). */
export const ADMISSIONS_CLOSED = 'ADMISSIONS_CLOSED';
/** Enrollment switch requires explicit student confirmation. */
export const ENROLLMENT_SWITCH_REQUIRED = 'ENROLLMENT_SWITCH_CONFIRMATION_REQUIRED';
/** Active enrollment already exists for this course. */
export const ENROLLMENT_ALREADY_ACTIVE = 'DUPLICATE_ACTIVE_ENROLLMENT';

/** CEE scoped query / DB enforcement */
export const CEE_MISSING_COURSE_SCOPE = 'CEE_MISSING_COURSE_SCOPE';
export const CEE_UNSCOPED_QUERY_DENIED = 'CEE_UNSCOPED_QUERY_DENIED';
export const CEE_INVALID_BYPASS = 'CEE_INVALID_BYPASS';
export const CEE_BYPASS_DENIED = 'CEE_BYPASS_DENIED';
export const CEE_PROTECTED_TABLE_ACCESS = 'CEE_PROTECTED_TABLE_ACCESS';
export const CEE_UNKNOWN_PROTECTED_ROUTE = 'CEE_UNKNOWN_PROTECTED_ROUTE';
export const CEE_PROTECTION_GRID_MISCONFIGURED = 'CEE_PROTECTION_GRID_MISCONFIGURED';

/** Payment & orders */
export const PAYMENT_REQUIRED = 'PAYMENT_REQUIRED';
export const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';
export const PAYMENT_ALREADY_FULFILLED = 'PAYMENT_ALREADY_FULFILLED';

/** HTTP / validation */
export const BAD_REQUEST = 'BAD_REQUEST';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const NOT_FOUND = 'NOT_FOUND';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const FORBIDDEN = 'FORBIDDEN';
export const CONFLICT = 'CONFLICT';
export const GONE = 'GONE';
export const RATE_LIMITED = 'RATE_LIMITED';
export const RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
export const PAYMENT_CHECKOUT_GLOBAL_BURST = 'PAYMENT_CHECKOUT_GLOBAL_BURST';
export const PAYMENT_CHECKOUT_USER_LIMIT = 'PAYMENT_CHECKOUT_USER_LIMIT';
export const PAYMENT_CHECKOUT_ENROLLMENT_LIMIT = 'PAYMENT_CHECKOUT_ENROLLMENT_LIMIT';
/** POST /api/enrollments create — per-user minute cap */
export const ENROLLMENT_CREATE_USER_PER_MINUTE = 'ENROLLMENT_CREATE_USER_PER_MINUTE';
/** POST /api/enrollments create — per-user hour cap */
export const ENROLLMENT_CREATE_USER_PER_HOUR = 'ENROLLMENT_CREATE_USER_PER_HOUR';
export const ENROLLMENT_CREATE_REDIS_REQUIRED = 'ENROLLMENT_CREATE_REDIS_REQUIRED';
/** POST test submit — per-user minute cap */
export const TEST_SUBMIT_USER_PER_MINUTE = 'TEST_SUBMIT_USER_PER_MINUTE';
export const TEST_SUBMIT_REDIS_REQUIRED = 'TEST_SUBMIT_REDIS_REQUIRED';
/** Test answer autosave — per-user minute cap */
export const AUTOSAVE_USER_PER_MINUTE = 'AUTOSAVE_USER_PER_MINUTE';
export const AUTOSAVE_REDIS_REQUIRED = 'AUTOSAVE_REDIS_REQUIRED';
export const PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE';
export const ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
export const INTERNAL_ERROR = 'INTERNAL_ERROR';

/** MySQL bootstrap */
export const MYSQL_ACCESS_DENIED = 'MYSQL_ACCESS_DENIED';
export const MYSQL_UNKNOWN_DATABASE = 'MYSQL_UNKNOWN_DATABASE';
export const MYSQL_SCHEMA_INCOMPLETE = 'MYSQL_SCHEMA_INCOMPLETE';
/** Pool queueLimit reached — fail fast instead of unbounded in-memory queue growth */
export const MYSQL_POOL_EXHAUSTED = 'MYSQL_POOL_EXHAUSTED';
/** Pool acquire wait exceeded MYSQL_POOL_ACQUIRE_TIMEOUT_MS */
export const MYSQL_POOL_ACQUIRE_TIMEOUT = 'MYSQL_POOL_ACQUIRE_TIMEOUT';
/** Query exceeded MYSQL_QUERY_TIMEOUT_MS */
export const MYSQL_QUERY_TIMEOUT = 'MYSQL_QUERY_TIMEOUT';
/** Transaction exceeded MYSQL_TRANSACTION_TIMEOUT_MS */
export const MYSQL_TRANSACTION_TIMEOUT = 'MYSQL_TRANSACTION_TIMEOUT';

/** Media */
export const MEDIA_ACCESS_DENIED = 'MEDIA_ACCESS_DENIED';
export const MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND';
export const UPLOAD_REJECTED = 'UPLOAD_REJECTED';

/** Test attempts (CEE) */
export const ATTEMPT_NOT_FOUND = 'ATTEMPT_NOT_FOUND';
export const ATTEMPT_NOT_OWNED = 'ATTEMPT_NOT_OWNED';
export const ATTEMPT_EXPIRED = 'ATTEMPT_EXPIRED';
export const ATTEMPT_INVALID_STATE = 'ATTEMPT_INVALID_STATE';
export const ATTEMPT_TOKEN_INVALID = 'ATTEMPT_TOKEN_INVALID';
export const COURSE_SCOPE_VIOLATION = 'COURSE_SCOPE_VIOLATION';
export const TEST_NOT_ACCESSIBLE = 'TEST_NOT_ACCESSIBLE';
export const LEGACY_ENDPOINT_DISABLED = 'LEGACY_ENDPOINT_DISABLED';
export const TEST_IS_LOCKED = 'TEST_IS_LOCKED';
export const QUESTION_MUTATION_NOT_ALLOWED = 'QUESTION_MUTATION_NOT_ALLOWED';
export const TEST_NOT_FOUND = 'TEST_NOT_FOUND';
export const QUESTION_NOT_IN_TEST = 'QUESTION_NOT_IN_TEST';
export const INVALID_OPTION = 'INVALID_OPTION';
export const QUESTION_DELETED = 'QUESTION_DELETED';
export const TEST_SUBJECTS_REQUIRED = 'TEST_SUBJECTS_REQUIRED';
export const QUESTION_SUBJECT_NOT_ALLOWED = 'QUESTION_SUBJECT_NOT_ALLOWED';
export const INVALID_TEST_COMPOSITION = 'INVALID_TEST_COMPOSITION';
export const INVALID_TEST_STATE = 'INVALID_TEST_STATE';
export const NO_SUBJECTS = 'NO_SUBJECTS';
export const PUBLISH_REQUIREMENTS_NOT_MET = 'PUBLISH_REQUIREMENTS_NOT_MET';
export const INVALID_CATEGORY = 'INVALID_CATEGORY';
export const INVALID_TEST_TYPE = 'INVALID_TEST_TYPE';

/** Question bank (admin) */
export const QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND';
export const INVALID_QUESTION_ID = 'INVALID_QUESTION_ID';

/** Quiz Builder drafts */
export const DRAFT_VERSION_CONFLICT = 'DRAFT_VERSION_CONFLICT';
export const QUIZ_DRAFT_NOT_FOUND = 'QUIZ_DRAFT_NOT_FOUND';

/** MCQ validation */
export const INVALID_MCQ_FOR_PUBLISH = 'INVALID_MCQ_FOR_PUBLISH';
