/**
 * Stable, machine-readable error codes for API responses, logging, analytics, and future i18n.
 *
 * Naming convention:
 * - SCREAMING_SNAKE_CASE
 * - Domain-prefixed where ambiguity exists (e.g. ACCESS_* for entitlement)
 * - Immutable once released — add new codes; never rename in place
 */

/** Authentication & session */
export const AUTH_REQUIRED = 'AUTH_REQUIRED';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const ADMIN_ACCESS_REQUIRED = 'ADMIN_ACCESS_REQUIRED';
export const STUDENT_ACCESS_REQUIRED = 'STUDENT_ACCESS_REQUIRED';
export const EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED';
export const STEP_UP_REQUIRED = 'STEP_UP_REQUIRED';
export const ACCOUNT_RISK_BLOCKED = 'ACCOUNT_RISK_BLOCKED';

/** Entitlement & enrollment access */
export const ENROLLMENT_NOT_FOUND = 'ENROLLMENT_NOT_FOUND';
export const ACCESS_EXPIRED = 'ACCESS_EXPIRED';
export const ACCESS_REVOKED = 'ACCESS_REVOKED';
export const ACCESS_INACTIVE = 'ACCESS_INACTIVE';
export const MULTIPLE_ACTIVE_ENROLLMENTS = 'MULTIPLE_ACTIVE_ENROLLMENTS';
export const COURSE_ACCESS_MISMATCH = 'COURSE_ACCESS_MISMATCH';
export const INVALID_ENTITLEMENT_STATE = 'INVALID_ENTITLEMENT_STATE';
export const COURSE_NOT_ACCESSIBLE = 'COURSE_NOT_ACCESSIBLE';
export const ENTITLEMENT_REQUIRED = 'ENTITLEMENT_REQUIRED';
export const ENROLLMENT_ACTIVATION_DENIED = 'ENROLLMENT_ACTIVATION_DENIED';
export const ENROLLMENT_INTEGRITY_VIOLATION = 'ENROLLMENT_INTEGRITY_VIOLATION';

/** CEE scoped query / DB enforcement */
export const CEE_MISSING_COURSE_SCOPE = 'CEE_MISSING_COURSE_SCOPE';
export const CEE_UNSCOPED_QUERY_DENIED = 'CEE_UNSCOPED_QUERY_DENIED';
export const CEE_INVALID_BYPASS = 'CEE_INVALID_BYPASS';
export const CEE_BYPASS_DENIED = 'CEE_BYPASS_DENIED';
export const CEE_PROTECTED_TABLE_ACCESS = 'CEE_PROTECTED_TABLE_ACCESS';
export const CEE_UNKNOWN_PROTECTED_ROUTE = 'CEE_UNKNOWN_PROTECTED_ROUTE';
export const CEE_PROTECTION_GRID_MISCONFIGURED = 'CEE_PROTECTION_GRID_MISCONFIGURED';

/** Payment & orders */
export const PAYMENT_REQUIRED = 'PAYMENT_REQUIRED';
export const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';
export const PAYMENT_ALREADY_FULFILLED = 'PAYMENT_ALREADY_FULFILLED';

/** HTTP / validation */
export const BAD_REQUEST = 'BAD_REQUEST';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const NOT_FOUND = 'NOT_FOUND';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const FORBIDDEN = 'FORBIDDEN';
export const CONFLICT = 'CONFLICT';
export const GONE = 'GONE';
export const RATE_LIMITED = 'RATE_LIMITED';
export const PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE';
export const ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
export const INTERNAL_ERROR = 'INTERNAL_ERROR';

/** MySQL bootstrap */
export const MYSQL_ACCESS_DENIED = 'MYSQL_ACCESS_DENIED';
export const MYSQL_UNKNOWN_DATABASE = 'MYSQL_UNKNOWN_DATABASE';
export const MYSQL_SCHEMA_INCOMPLETE = 'MYSQL_SCHEMA_INCOMPLETE';

/** Media */
export const MEDIA_ACCESS_DENIED = 'MEDIA_ACCESS_DENIED';
export const MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND';
export const UPLOAD_REJECTED = 'UPLOAD_REJECTED';

/** Test attempts (CEE) */
export const ATTEMPT_NOT_FOUND = 'ATTEMPT_NOT_FOUND';
export const ATTEMPT_NOT_OWNED = 'ATTEMPT_NOT_OWNED';
export const ATTEMPT_EXPIRED = 'ATTEMPT_EXPIRED';
export const ATTEMPT_INVALID_STATE = 'ATTEMPT_INVALID_STATE';
export const ATTEMPT_TOKEN_INVALID = 'ATTEMPT_TOKEN_INVALID';
export const COURSE_SCOPE_VIOLATION = 'COURSE_SCOPE_VIOLATION';
export const TEST_NOT_ACCESSIBLE = 'TEST_NOT_ACCESSIBLE';

/** Question bank (admin) */
export const QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND';
export const INVALID_QUESTION_ID = 'INVALID_QUESTION_ID';
