/** Action type constants — single source for reducer dispatch. */

export const CREATE_QUESTION_ACTIONS = Object.freeze({
  SET_METADATA_FIELD: 'SET_METADATA_FIELD',
  SET_QUESTION_TEXT: 'SET_QUESTION_TEXT',
  UPDATE_OPTION_TEXT: 'UPDATE_OPTION_TEXT',
  UPDATE_OPTION_IMAGE: 'UPDATE_OPTION_IMAGE',
  SET_CORRECT_OPTION: 'SET_CORRECT_OPTION',
  RESET_OPTIONS: 'RESET_OPTIONS',
  SET_EXPLANATION_TEXT: 'SET_EXPLANATION_TEXT',
  SET_QUESTION_IMAGE: 'SET_QUESTION_IMAGE',
  REMOVE_QUESTION_IMAGE: 'REMOVE_QUESTION_IMAGE',
  SET_UI_LOADING: 'SET_UI_LOADING',
  SET_FIELD_ERRORS: 'SET_FIELD_ERRORS',
  CLEAR_FIELD_ERROR: 'CLEAR_FIELD_ERROR',
  SET_PREVIEW_VISIBLE: 'SET_PREVIEW_VISIBLE',
  RESET_FORM: 'RESET_FORM',
});
